import type { Metadata } from "next";
import "./globals.css";
import { archivo_black } from "./lib/fonts";

export const metadata: Metadata = {
  title: "Spot Check",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${archivo_black.variable}`}>
      <body className="min-h-full flex flex-col">{children}</body>

      <script
        src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
        crossOrigin=""
      ></script>
    </html>
  );
}
