import type { Metadata } from "next";
import "./globals.css";
import { archivo_black } from "./lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${archivo_black.variable}`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
